baseURL = 'https://stirring-selkie-92d0f5.netlify.app'
languageCode = 'en-us'
title = 'Pricing information | aspose.conholdate.com'
theme = 'pricing'
draft = "false"

[module]
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'en'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'de'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'zh'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'ja'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'ru'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'it'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'es'
  [[module.mounts]]
    source = 'prebuild/public/product'
    target = 'content/pricing'
    lang = 'fr'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'en'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'de'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'zh'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'ja'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'ru'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'it'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'es'
  [[module.mounts]]
    source = 'themes/pricing/content'
    target = 'content/pricing'
    lang = 'fr'
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'assets'
  

[params]
    url = "https://purchase-api.dynabic.com/v1.2/productFamily/site-conholdate?isArchived=&pageNumber=&pageSize=&applyDisplayOrder=true&includeProducts=false"


[params.dynamicmenuid]
  en = "conholdate-en"
  de = "conholdate-de"
  zh = "conholdate-zh"
  ja = "conholdate-ja"
  ru = "conholdate-ru"
  it = "conholdate-it"
  es = "conholdate-es"
  fr = "conholdate-fr"

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
publishDir = "public/content/pricing"
[languages]
  [languages.de]
    languageName = 'Deutsch'
    contentDir = 'content/pricing/de'
    languageCode = "de"
    flag = "flag-de"
    title = "Preisinformationen | conholdate.com"
    weight = 4
  [languages.en]
    languageName = 'English'
    contentDir = 'content/pricing/en'
    flag = "flag-us"
    languageCode = "en"
    title = "Pricing information | conholdate.com"
    weight = 3
  [languages.zh]
    languageName = '简体中文'
    contentDir = 'content/pricing/zh'
    flag = "flag-zh"
    languageCode = "zh"
    title = "定价信息 | conholdate.com"
    weight = 1
  [languages.ja]
    languageName = '日本語'
    contentDir = 'content/pricing/ja'
    flag = "flag-ja"
    languageCode = "ja"
    title = "価格情報 | conholdate.com"
    weight = 2
  [languages.ru]
    languageName = 'Русский'
    contentDir = 'content/pricing/ru'
    flag = "flag-ru"
    languageCode = "ru"
    title = "Информация о ценах | conholdate.com"
    weight = 5
  [languages.it]
    languageName = 'Italiano'
    contentDir = 'content/pricing/it'
    flag = "flag-it"
    languageCode = "it"
    title = "Informazioni sui prezzi | conholdate.com"
    weight = 6
  [languages.es]
    languageName = 'Español'
    contentDir = 'content/pricing/es'
    flag = "flag-es"
    languageCode = "es"
    title = "Información de precio | conholdate.com"
    weight = 7
  [languages.fr]
    languageName = 'Français'
    contentDir = 'content/pricing/fr'
    flag = "flag-fr"
    languageCode = "fr"
    title = "Information sur les prix | conholdate.com"
    weight = 8
